import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/1.0.module.css";
import { Layout } from "./components/layout";
import iphone from "../public/iphone.png";
import naixue from "../public/naixue.jpg";
import badgeL from "../public/badge-light.png";
import badgeD from "../public/badge-dark.png";
import { useRouter } from "next/router";

export default function Page() {
  const router = useRouter();

  const { login } = router.query

  console.log('login =', login);

  return (
    <>
      <Head>
        <title>数云联盟联合活动页</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/sylogo.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <Image
            className={styles.iphone}
            src={iphone}
            width={340}
            alt="13"
            priority
          />
          <Image
            className={styles.naixue}
            src={naixue}
            width={340}
            alt="13"
            priority
          />
          <span className={styles.text}>
            点亮下方徽章，前往线下门店获取礼品。
          </span>

          <div className={styles.badgeContainer}>
            <div style={{ marginRight: -5, position: 'relative', cursor: 'pointer', zIndex: 10000 }}>
              <Image
                className={styles.badgeImg}
                src={badgeL}
                alt="13"
                priority
              />
              <span
                className={styles.badgeText}
                style={{
                  backgroundColor: "#a8ca49",
                  color: "#ffffff",
                  fontSize: 9,
                  fontWeight: "bold",
                  padding: "0 2px",
                  right: 12,
                  top: 16
                }}
              >
                奈雪
              </span>
            </div>

            <div onClick={() => router.push('signup')} style={{ position: 'relative', cursor: 'pointer', zIndex: 10000 }}>
              <Image
                className={styles.badgeImg}
                src={login === 'true' ? badgeL : badgeD}
                alt="13"
                priority
              />
              <span
                className={styles.badgeText}
                style={{
                  // backgroundColor: "#4383b5",
                  backgroundColor: '#717171',
                  color: "#ffffff",
                  fontSize: 9,
                  fontWeight: "bold",
                  padding: "0 2px",
                  right: 7,
                  top: 16
                }}
              >
                可爱多
              </span>
            </div>
          </div>
        </div>
        {/* <Image src="/kele_action.png" alt="13" width={40} height={31} priority /> */}
      </main>
    </>
  );
}
