import Head from "next/head";
import { useRouter } from "next/router";
import { Input, Button, Checkbox, Spacer } from "@nextui-org/react";
import { useEffect, useState } from "react";
import styles from "../styles/signup.module.css";
import { message, Spin } from "antd";
import { Box } from "./components/box";

interface SignUpFormData {
  username: string;
  phone: string;
  password: string;
  password2: string;
  agreeNaiXue: boolean;
  agreeKeAiDuo: boolean;
}

export default function Page() {
  const router = useRouter();

  const [messageApi, contextHolder] = message.useMessage();

  const [showMessage, setShowMessage] = useState(false);

  const [formData, setFormData] = useState<SignUpFormData>({
    username: "",
    phone: "",
    password: "",
    password2: "",
    agreeNaiXue: false,
    agreeKeAiDuo: false,
  });

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement>,
    key: keyof SignUpFormData,
    checked?: boolean
  ) => {
    setFormData({
      ...formData,
      [key]: checked ? e : e.target.value,
    });
  };

  const handleSubmit = () => {
    // console.log(formData);
    // 提交注册信息到服务器的代码
    message.success("注册成功，即将跳转至活动页面", 1);

    // messageApi.open({
    //   type: "success",
    //   content: "注册成功，即将跳转至活动页面",
    //   duration: 1,
    // });

    setTimeout(() => {
      setShowMessage(true);
    }, 1000);

    setTimeout(() => {
      router.push("/1.0?login=true"); // 注册成功后跳转到 success 页面
    }, 2000);
  };

  return (
    <>
      <Head>
        <title>数云联盟联合注册页</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/sylogo.ico" />
      </Head>

      <main className={styles.container}>
        <Input
          fullWidth
          size="sm"
          label="用户名"
          placeholder="请输入用户名"
          //   required
          //   value={formData.username}
          //   onChange={(e) => handleChange(e, "username")}
        />
        <Spacer y={0.5} />
        <Input
          fullWidth
          size="sm"
          label="手机号"
          placeholder="请输入手机号"
          //   required
          //   value={formData.phone}
          //   onChange={(e) => handleChange(e, "phone")}
        />
        <Spacer y={0.5} />
        <Input.Password
          fullWidth
          size="sm"
          label="密码"
          placeholder="请输入密码"
          //   required
          //   value={formData.password}
          //   onChange={(e) => handleChange(e, "password")}
        />
        <Spacer y={0.5} />
        <Input.Password
          fullWidth
          size="sm"
          label="确认密码"
          placeholder="请再次输入密码"
          //   required
          //   value={formData.password2}
          //   onChange={(e) => handleChange(e, "password2")}
        />

        <Spacer y={1.5} />

        <Button
          style={{ backgroundColor: "#0072f5", width: "100%" }}
          onPress={handleSubmit}
        >
          注册并登录
        </Button>

        <Spacer y={1.5} />
        <div className={styles.checkboxGroup}>
          <Checkbox
          // isSelected={formData.agreeNaiXue}
          // onChange={(e) => handleChange(e, "agreeNaiXue", true)}
          >
            <span className={styles.checkboxText}>
              我同意《奈雪的茶服务协议》
            </span>
          </Checkbox>
          <Spacer y={0.5} />
          <Checkbox
          // isSelected={formData.agreeKeAiDuo}
          // onChange={(e) => handleChange(e, "agreeKeAiDuo", true)}
          >
            <span className={styles.checkboxText}>
              我同意《可爱多服务协议》
            </span>
          </Checkbox>
        </div>

        <Spacer y={6} />

        <footer className={styles.footer}>
          Powered by <a href="https://nextui.org/">Shuyun</a>
        </footer>
      </main>

      {showMessage ? (
        <Box
          css={{
            position: "absolute",
            top: 0,
            left: 0,
            width: "100vw",
            height: "100vh",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <Spin size="large" style={{ marginTop: 400 }} />
        </Box>
      ) : null}
    </>
  );
}
